import pandas as pd

entries = [
    ("NY Times", "nytimes.com", "News", "Non-Slop"),
    ("BBC News", "bbc.co.uk/news", "News", "Non-Slop"),
    ("Reuters", "reuters.com", "News", "Non-Slop"),
    ("The Economist", "economist.com", "News", "Non-Slop"),
    ("AP News", "apnews.com", "News", "Non-Slop"),
    ("Infowars", "infowars.com", "News", "Slop"),
    ("Celebrities Deaths", "celebritiesdeaths.com", "News", "Slop"),
    ("Ireland Top News", "irelandtopnews.com", "News", "Slop"),
    ("Daily Mail", "dailymail.co.uk", "News", "Slop"),
    ("The People's Voice", "thepeoplesvoice.tv", "News", "Slop"),
    ("Wired", "wired.com", "Tech", "Non-Slop"),
    ("Ars Technica", "arstechnica.com", "Tech", "Non-Slop"),
    ("TechCrunch", "techcrunch.com", "Tech", "Non-Slop"),
    ("Stack Overflow", "stackoverflow.com", "Tech", "Non-Slop"),
    ("CNET", "cnet.com", "Tech", "Non-Slop"),
    ("TechTarget", "techtarget.com", "Tech", "Non-Slop"),
    ("Best Budget USA", "bestbudgetusa.com", "Tech", "Slop"),
    ("T News Network", "tnewsnetwork.com", "Tech", "Slop"),
    ("Zac Johnson", "zacjohnson.com", "Tech", "Slop"),
    ("Harmony Hustle", "harmonyhustle.com", "Tech", "Slop"),
    ("Mayo Clinic", "mayoclinic.org", "Health", "Non-Slop"),
    ("WebMD", "webmd.com", "Health", "Non-Slop"),
    ("Healthline", "healthline.com", "Health", "Non-Slop"),
    ("MedlinePlus", "nih.gov/medlineplus", "Health", "Non-Slop"),
    ("Natural News", "naturalnews.com", "Health", "Slop"),
    ("Mercola", "mercola.com", "Health", "Slop"),
    ("GreenMedInfo", "greenmedinfo.com", "Health", "Slop"),
    ("Top 10 Home Remedies", "top10homeremedies.com", "Health", "Slop"),
    ("Health Tips Blog", "healthtipsblog.xyz", "Health", "Slop"),
    ("WSJ", "wsj.com", "Finance", "Non-Slop"),
    ("Investopedia", "investopedia.com", "Finance", "Non-Slop"),
    ("Bloomberg", "bloomberg.com", "Finance", "Non-Slop"),
    ("Consumer Reports", "consumerreports.org", "Finance", "Non-Slop"),
    ("Filthy Lucre", "filthylucre.com", "Finance", "Slop"),
    ("Being Selfish", "beingselfish.in", "Finance", "Slop"),
    ("Equity Atlas", "equityatlas.org", "Finance", "Slop"),
    ("Popular Net Worth", "popularnetworth.com", "Finance", "Slop"),
    ("Top Credit Cards Reviews", "topcreditcardsreviews.biz", "Finance", "Slop"),
    ("Benzinga", "benzinga.com", "Finance", "Slop"),
    ("Wikipedia", "en.wikipedia.org", "Reference", "Non-Slop"),
    ("Britannica", "britannica.com", "Reference", "Non-Slop"),
    ("Stanford Encyclopedia", "plato.stanford.edu", "Reference", "Non-Slop"),
    ("Khan Academy", "khanacademy.org", "Reference", "Non-Slop"),
    ("eHow", "ehow.com", "Reference", "Slop"),
    ("Buzzle", "buzzle.com", "Reference", "Slop"),
    ("Ezine Articles", "ezinearticles.com", "Reference", "Slop"),
    ("NCERT Point", "ncertpoint.com", "Reference", "Slop"),
    ("Brainly", "brainly.com", "Reference", "Slop"),
    ("Cheat Essays Blog", "cheat essays blog", "Reference", "Slop"),
    ("Wirecutter", "wirecutter.com", "Reviews", "Non-Slop"),
    ("Consumer Reports", "consumerreports.org", "Reviews", "Non-Slop"),
    ("RTINGS", "rtings.com", "Reviews", "Non-Slop"),
    ("Tom's Hardware", "tomshardware.com", "Reviews", "Non-Slop"),
    ("Tom's Guide", "tomsguide.com", "Reviews", "Non-Slop"),
    ("Famadillo", "famadillo.com", "Reviews", "Slop"),
    ("SI.com", "si.com", "Reviews", "Slop"),
    ("Top Ten Reviews", "toptenreviews.com", "Reviews", "Slop"),
    ("Best X For Y", "bestxfory.com", "Reviews", "Slop"),
    ("People", "people.com", "Lifestyle", "Non-Slop"),
    ("Variety", "variety.com", "Lifestyle", "Non-Slop"),
    ("AllRecipes", "allrecipes.com", "Lifestyle", "Non-Slop"),
    ("Snopes", "snopes.com", "Lifestyle", "Non-Slop"),
    ("Bored Panda", "boredpanda.com", "Lifestyle", "Slop"),
    ("BuzzFeed", "buzzfeed.com", "Lifestyle", "Slop"),
    ("Popular Bio", "popularbio.com", "Lifestyle", "Slop"),
    ("Married Biography", "marriedbiography.com", "Lifestyle", "Slop"),
    ("TopTenz", "toptenz.net", "Lifestyle", "Slop"),
    ("Listverse", "listverse.com", "Lifestyle", "Slop"),
]

sources_df = pd.DataFrame(entries, columns=["website_name", "url", "domain", "slop"])
